version: 0.2

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 469735151043.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - docker build -t nestjs-ability -f ./Dockerfile.prod .
      - docker tag nestjs-ability:latest 469735151043.dkr.ecr.us-east-1.amazonaws.com/nestjs-ability:latest
  post_build:
    commands:
      - docker push 469735151043.dkr.ecr.us-east-1.amazonaws.com/nestjs-ability:latest