FROM node:18.8.0

USER node

RUN mkdir -p /home/node/app/backend

WORKDIR /home/node/app/backend

COPY --chown=node:node . .

RUN npm install
RUN npm run prisma:dev:generate
RUN npm run build

EXPOSE 5000

CMD [ "npm", "run", "start:prod"]