FROM node:18.8.0

USER node

RUN mkdir -p /home/node/app

WORKDIR /home/node/app

COPY --chown=node:node . .

RUN ls
RUN cd backend/
RUN cd backend/ & ls
RUN cd backend/ & npm install
RUN cd backend/ & npm run prisma:dev:generate
RUN cd backend/ & npm run build

EXPOSE 5000

CMD [ "npm", "run", "start:prod"]